### ISSUE TITLE
Keep getting this error?

### ISSUE THREAD

**Issue by BusterBean** [TheAlienDrew/Tampermonkey-Scripts#2]
Minecraft Music Bot (v2.4.4): Error! (play) InvalidCharacterError: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by TheAlienDrew** [comment]
I'm not an expert on this particular error, but I suggest renaming your MIDI file to something simple and then trying it again.

**Comment by TheAlienDrew** [comment]
Did renaming the midi file fix your issue? @BusterBean

**Comment by TheAlienDrew** [comment]
I see now that this is for the Minecraft Music Bot... by default I don't include the original songs, since I had to buy the sheet music album to create the MIDI files by hand. Since it's copyrighted work, I can't include that in my open-source program.

If you want to use the bot with Minecraft MIDI's, find versions of the songs online, and edit the script file to include data uris of the files you are using.
